'use client'

import { useState } from 'react'
import { Copy, CheckCircle, Download, ExternalLink, Code2, X } from 'lucide-react'
import type { GeneratedScript } from '@/types'

interface Props {
  script: GeneratedScript
  onClose?: () => void
}

const TEMPLATE_LABELS = {
  anomaly: 'Anomaly Detection',
  sentiment: 'Sentiment Analysis',
  timeseries: 'Time Series Forecast',
}

const TEMPLATE_COLORS = {
  anomaly: 'text-red-400',
  sentiment: 'text-yellow-400',
  timeseries: 'text-cyan',
}

// Simple syntax highlighter using regex
function HighlightedCode({ code }: { code: string }) {
  // Split into lines and apply basic highlighting
  const lines = code.split('\n')

  function tokenizeLine(line: string) {
    // Comments
    if (line.trimStart().startsWith('#')) {
      return <span className="text-slate-500">{line}</span>
    }
    // Apply simple replacements
    const tokens: React.ReactNode[] = []
    let rest = line

    // Keywords
    const keywordRe = /\b(import|from|as|def|class|if|else|elif|for|in|while|try|except|return|True|False|None|and|or|not|with|is|lambda|yield|raise|pass|break|continue|global|nonlocal)\b/g
    rest = rest.replace(keywordRe, m => `__KW__${m}__KW__`)
    // Strings
    rest = rest.replace(/("""[\s\S]*?"""|'''[\s\S]*?'''|"[^"\\]*(?:\\.[^"\\]*)*"|'[^'\\]*(?:\\.[^'\\]*)*')/g, m => `__STR__${m}__STR__`)
    // Numbers
    rest = rest.replace(/\b(\d+\.?\d*)\b/g, m => `__NUM__${m}__NUM__`)
    // Builtins / functions
    rest = rest.replace(/\b(print|len|range|list|dict|str|int|float|bool|type|isinstance|enumerate|zip|map|filter|sorted|set|tuple|any|all|max|min|sum|abs|round|open|super|self)\b/g, m => `__BUILTIN__${m}__BUILTIN__`)

    // Split on markers and render
    const parts = rest.split(/(__KW__|__STR__|__NUM__|__BUILTIN__)/)
    let type = 'default'
    for (const part of parts) {
      if (part === '__KW__') { type = 'kw'; continue }
      if (part === '__STR__') { type = 'str'; continue }
      if (part === '__NUM__') { type = 'num'; continue }
      if (part === '__BUILTIN__') { type = 'bi'; continue }
      if (!part) continue
      if (type === 'kw') tokens.push(<span key={tokens.length} className="text-accent-light">{part}</span>)
      else if (type === 'str') tokens.push(<span key={tokens.length} className="text-green-400">{part}</span>)
      else if (type === 'num') tokens.push(<span key={tokens.length} className="text-cyan">{part}</span>)
      else if (type === 'bi') tokens.push(<span key={tokens.length} className="text-amber-400">{part}</span>)
      else tokens.push(<span key={tokens.length} className="text-slate-300">{part}</span>)
      type = 'default'
    }
    return <>{tokens}</>
  }

  return (
    <div className="overflow-x-auto">
      <pre className="p-4 text-xs font-mono leading-5 min-w-max">
        {lines.map((line, i) => (
          <div key={i} className="flex">
            <span className="mr-4 select-none text-right text-slate-700" style={{ minWidth: '2.5rem' }}>
              {i + 1}
            </span>
            <span>{tokenizeLine(line)}</span>
          </div>
        ))}
      </pre>
    </div>
  )
}

function encodeAsColabUrl(code: string): string {
  // Opens a new blank Colab — code is too long to embed in URL, so we guide user to paste
  return 'https://colab.research.google.com/#create=true'
}

export default function ScriptOutput({ script, onClose }: Props) {
  const [copied, setCopied] = useState(false)
  const lineCount = script.code.split('\n').length

  function copyCode() {
    navigator.clipboard.writeText(script.code).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    })
  }

  function downloadScript() {
    const blob = new Blob([script.code], { type: 'text/x-python' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = script.filename
    a.click()
    URL.revokeObjectURL(url)
  }

  function downloadNotebook() {
    const notebook = {
      nbformat: 4,
      nbformat_minor: 5,
      metadata: {
        kernelspec: { display_name: 'Python 3', language: 'python', name: 'python3' },
        language_info: { name: 'python', version: '3.10.0' },
      },
      cells: [
        {
          cell_type: 'markdown',
          metadata: {},
          source: [`# RaffleML — ${TEMPLATE_LABELS[script.template]}\n`, `Generated by [RaffleML](https://github.com/genjess/raffleml)`],
        },
        {
          cell_type: 'code',
          metadata: {},
          execution_count: null,
          outputs: [],
          source: script.code.split('\n').map((l, i, a) => i < a.length - 1 ? l + '\n' : l),
        },
      ],
    }
    const blob = new Blob([JSON.stringify(notebook, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = script.filename.replace('.py', '.ipynb')
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="rounded-xl border border-border bg-card overflow-hidden animate-slide-up">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-border px-5 py-3.5">
        <div className="flex items-center gap-2.5">
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-accent/15 ring-1 ring-accent/30">
            <Code2 className="h-4 w-4 text-accent-light" />
          </div>
          <div>
            <p className="text-sm font-semibold text-slate-200">
              Generated Script
              <span className={`ml-2 text-xs ${TEMPLATE_COLORS[script.template]}`}>
                {TEMPLATE_LABELS[script.template]}
              </span>
            </p>
            <p className="text-[10px] text-slate-500">
              {script.filename} · {lineCount} lines
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          {/* Copy */}
          <button
            onClick={copyCode}
            className={`flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium ring-1 transition-all ${
              copied
                ? 'bg-green-500/15 text-green-400 ring-green-500/30'
                : 'bg-card text-slate-300 ring-border hover:ring-accent/50 hover:text-white'
            }`}
          >
            {copied ? (
              <CheckCircle className="h-3.5 w-3.5" />
            ) : (
              <Copy className="h-3.5 w-3.5" />
            )}
            {copied ? 'Copied!' : 'Copy'}
          </button>

          {/* Download .py */}
          <button
            onClick={downloadScript}
            className="flex items-center gap-1.5 rounded-lg bg-card px-3 py-1.5 text-xs font-medium text-slate-300 ring-1 ring-border transition-all hover:ring-accent/50 hover:text-white"
          >
            <Download className="h-3.5 w-3.5" />
            .py
          </button>

          {/* Download .ipynb */}
          <button
            onClick={downloadNotebook}
            className="flex items-center gap-1.5 rounded-lg bg-accent/15 px-3 py-1.5 text-xs font-medium text-accent-light ring-1 ring-accent/30 transition-all hover:bg-accent/25"
          >
            <Download className="h-3.5 w-3.5" />
            .ipynb
          </button>

          {/* Open Colab */}
          <a
            href={encodeAsColabUrl(script.code)}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-1.5 rounded-lg bg-[#F9AB00]/10 px-3 py-1.5 text-xs font-medium text-[#F9AB00] ring-1 ring-[#F9AB00]/30 transition-all hover:bg-[#F9AB00]/20"
          >
            <ExternalLink className="h-3.5 w-3.5" />
            Open Colab
          </a>

          {onClose && (
            <button
              onClick={onClose}
              className="rounded-lg p-1.5 text-slate-600 transition-colors hover:text-slate-300"
            >
              <X className="h-4 w-4" />
            </button>
          )}
        </div>
      </div>

      {/* Colab tip */}
      <div className="flex items-center gap-2 border-b border-border bg-[#F9AB00]/5 px-5 py-2.5">
        <span className="text-[10px] text-[#F9AB00]/70">
          💡 <strong className="text-[#F9AB00]">Colab tip:</strong> Click "Open Colab", then press{' '}
          <kbd className="rounded bg-[#F9AB00]/15 px-1 py-0.5 font-mono">Ctrl+V</kbd> to paste the copied script,
          or download the <strong>.ipynb</strong> file and open it directly in Colab via File → Upload notebook.
        </span>
      </div>

      {/* Code */}
      <div className="max-h-[520px] overflow-y-auto bg-[#0d1117]">
        <HighlightedCode code={script.code} />
      </div>
    </div>
  )
}
